### ISSUE TITLE
Inconsistent output of FoodExpanditure() and consumptionValue(..., type="food") functions 

### ISSUE THREAD

**Issue by mishkos** [pik-piam/magpie4#2]
Ideally this should be the same. For the difference between the output of `FoodExpenditure()` and `consumptionValue(..., type="food")`, it basically comes from usage of different approaches for calculation of prices and quantities, the former using prices per kcal and caloric intake and the latter using prices per tones DM and tDM consumption. Since prices in both case are calculated as Lagrangian multipliers, it could be that the difference in output of functions comes from a general equation system setup in magpie and related interplay between demand variables.

**Comment by tscheypidi** [comment]
has this been fixed yet?

**Comment by bodirsky** [comment]
I do not understand the issue, and miskos answer..

**Comment by bodirsky** [comment]
ok, this is the issue:

> b=consumptionValue("../../inputdata/fulldata.gdx", type="food")[,"y2050",]
> sum(b)
[1] 5660919
> a=FoodExpenditure("../../inputdata/fulldata.gdx")[,2050,]
> sum(a)
[1] 7855.305
> b=consumptionValue("../../inputdata/fulldata.gdx", type="food")[,"y2050",]
> sum(b)
[1] 5660919

**Comment by bodirsky** [comment]
the food expenditure function calculates expenditure based on calories and calorie-prices:
price = readGDX(gdx,"p15_prices_kcal")
which in the gams code is the equation

p15_prices_kcal(t,iso,kfo)=sum(i_to_iso(i,iso), q15_food_demand.m(i,kfo));
q15_food_demand(i2,kfo) ..
                (vm_dem_food(i2,kfo) + sum(ct, f15_household_balanceflow(ct,i2,kfo,"dm")))
                * sum(ct,(f15_nutrition_attributes(ct,kfo,"kcal") * 10**6)) =g=
                sum(ct,im_pop(ct,i2) * p15_kcal_pc_calibrated(ct,i2,kfo)) * 365
                ;
the calories come from the parameter
readGDX(gdx=gdx,"p15_kcal_pc_iso")



the consumption value function receives its prices from the equation:
    d <- readGDX(gdx,"ov_supply",select = list(type="level"),react = "warning")
and the quantities from the variable
 readGDX(gdx, "ov_dem_food", select=list(type="level"))

**Comment by bodirsky** [comment]
So i see one bug in the food expenditure function, because it omits the multiplication by 365.
This still does not close the gap (still ~50%)

**Comment by bodirsky** [comment]
ah, no. the multiplication by 365 is done.

**Comment by bodirsky** [comment]
ah, the food expenditure is by default as per-capita.
if you switch it to per-capita = FALSE, it provides similar values as the consumption value

a = FoodExpenditure(gdx,per_capita=FALSE)[,2050,]
> sum(a)
[1] 5787212

b=consumptionValue("../../inputdata/fulldata.gdx", type="food")[,"y2050",]
sum(b)
[1] 5660919


so everything is fine, no bugs :)
