### ISSUE TITLE
.filtermagpie

### ISSUE THREAD

**Issue by bodirsky** [pik-piam/magpie4#3]
beim ausführen der Funktion getReportMAgPIE2LPJmL in magpie4 bekomme ich folgenden Fehler in der subroutine .filtermagpie

 
Error in Ops.units(u1, u2) : operation | not allowed
 
die funktion ist folgende:

.tmp <- function(mstat,filter) {
    tmp <- FALSE
    for(f in filter) {
      tmp <- tmp | (mstat==f) 
    }
    return(tmp)
  }

ich verstehen auch nciht was das hier tmp | (mstat==f)  zurückliefern soll.

> tmp
[1] FALSE
> filter
[1] 2 7
> mstat
An object of class "magpie"
, ,  = main

     t
      y1995 y2000 y2005 y2010 y2015 y2020 y2025 y2030 y2035 y2040 y2045 y2050 y2055 y2060 y2070 y2080 y2090 y2100
  GLO     2     2     2     2     2     2     2     2     2     2     2     2     2     2     2     2     2     2

ich glaube das geht nur mit einem modelstat, kann das sein?

**Comment by tscheypidi** [comment]
Did you run that part of code with metadata activated (withMetadata()=TRUE)? 
It looks to me that the metadata check for units failed in this case. If so, I would like to close the issue as metadata handling is still experimental and needs a major overhaul before it can be used productively.

**Comment by tscheypidi** [comment]
I forgot to mention: the line `tmp | (mstat==f)` is probably not very efficient but should work properly as it is executed in a for loop over all states filter. Hence, each filter state is tested separately, so that a vector of filter variables does not cause any problems with the `==` statement
