### ISSUE TITLE
magpie4 on cluster

### ISSUE THREAD

**Issue by abhimishr** [pik-piam/magpie4#4]
magpie4 seems to have disappeared from installed packages on cluster.

An R session on clutser provides this error

```
library(magpie4)
Error in library(magpie4) : there is no package called 'magpie4'
```

Checking for `version magpie4` on cluster provides the following message

```
Package: magpie4
Installed version: <not installed>
Last updated: <never>

Availability in repositories:
<not available> | https://cran.rstudio.com/
1.66.0 | http://www.pik-potsdam.de/rd3mod/R/
1.65.0 | https://rse.pik-potsdam.de/r/packages/
```

Trying to make two sets to check CONOPT4 settings and it is not possible at the moment to make these tests on cluster without this package availability.

**Comment by tscheypidi** [comment]
package is available again. Not sure why it got lost in the process.
