### ISSUE TITLE
Kcal(gdx, level="regglo", after_shock=FALSE, calibrated=FALSE) does not return a time series

### ISSUE THREAD

**Issue by tscheypidi** [pik-piam/magpie4#7]
In contrast to all other combinations of after_shock TRUE/FALSE and calibrated TRUE/FALSE, the combination after_shock=FALSE and calibrated=FALSE does not return a time series. 
This is counter intuitive to me and is causing some problems with functions such as PriceElasticities.

Is that intended or is that a mistake?

**Comment by bodirsky** [comment]
solved
